# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
