# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190820_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.CharField(blank=True, choices=[('Смартфон', 'Смартфон'), ('Ноутбук', 'Ноутбук')], default='Смартфон', max_length=15),
        ),
    ]
