# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190821_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='images/shop', verbose_name='Ссылка картинки'),
        ),
    ]
