# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-18 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190821_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
